language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

install:
  - composer update
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar -O coveralls.phar
  - chmod +x coveralls.phar
  - sudo mv coveralls.phar /usr/local/bin/coveralls
  - coveralls --version
  - sudo mv example/example.conf ./

bofore_script:
  - mkdir -p build/logs
  - ls -al

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit --bootstrap vendor/autoload.php tests/ -c phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - coveralls -v
  - bash <(curl -s https://codecov.io/bash)
